apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - applications/postgresql-app.yaml
  - applications/gitea-app.yaml
# You can add patches or other customizations here if needed.
# For example, to change the service type for the Argo CD server:
# patchesStrategicMerge:
#   - |
#     apiVersion: v1
#     kind: Service
#     metadata:
#       name: argocd-server
#       namespace: argocd
#     spec:
#       type: LoadBalancer
#       externalTrafficPolicy: Local
