apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
  namespace: gitea-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: GITEA_ADMIN_USERNAME
      remoteRef:
        key: GITEA_ADMIN_USERNAME
    - secretKey: GITEA_ADMIN_PASSWORD
      remoteRef:
        key: GITEA_ADMIN_PASSWORD
    - secretKey: GITEA_ADMIN_EMAIL
      remoteRef:
        key: GITEA_ADMIN_EMAIL
