apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: gitea-system
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
type: Opaque
data:
  # GITEA_SECRET_KEY: Base64 encoded random string (e.g., head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 | base64)
  GITEA_SECRET_KEY: GSyZnzFWGK8Fy4/gCUcxOSUlA0UosvPQuhRbFPdpAv4=
