apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: a5b45d5975b639a4a7c52bce1a977081
  AUTH_SECRET: "Co+XeE0Vi2x3Fvo9bc2uwzGgv/vLflQdCPCNRNgtUtc="
