apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: gitea-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: POSTGRES_DB
    - secretKey: GITEA_DB_PASSWORD
      remoteRef:
        key: GITEA_DB_PASSWORD
