apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-hba-config
  namespace: gitea-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea-db
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5
