apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: gitea-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea-db
type: Opaque
data:
  POSTGRES_PASSWORD: xWBl3bx5Nh3fKolPRZLFduS4BzoYQvvbRMgL1J9X214=
  POSTGRES_USER: gitea
  POSTGRES_DB: gitea
  GITEA_DB_PASSWORD: VJEtHXBtiDFEjkxN0I64aBrgPggCoX/hzxhI9w2DOrA=
