apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: gitea-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea-db
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
