apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Databases and persistent data stores
  sourceRepos:
    - git@github.com:holdennguyen/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: gitea-system
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
