apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-machine-identity
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-machine-identity
            namespace: external-secrets
