apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: git
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:holdennguyen/homelab.git
    targetRevision: HEAD
    path: k8s/apps/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # Namespace is created by the PostgreSQL application
