apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: "1.7.2"
    helm:
      # postgres and redis passwords are injected from the infisical-helm-secrets K8s
      # Secret (created by Terraform). They are never stored in git.
      valuesFrom:
        - kind: Secret
          name: infisical-helm-secrets
      valuesObject:
        infisical:
          replicaCount: 1
          # infisical-secrets contains ENCRYPTION_KEY and AUTH_SECRET,
          # created by Terraform (bootstrap-secrets.tf).
          kubeSecretRef: infisical-secrets
          service:
            type: NodePort
            nodePort: "30445"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1500Mi
        ingress:
          enabled: false
        postgresql:
          enabled: true
          fullnameOverride: "postgresql"
          auth:
            username: infisical
            database: infisicalDB
            # password key is provided via valuesFrom → infisical-helm-secrets
        redis:
          enabled: true
          fullnameOverride: "redis"
          architecture: standalone
          # auth.password is provided via valuesFrom → infisical-helm-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
