apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
    homelab/tier: data
    homelab/category: database
spec:
  project: data
  source:
    repoURL: git@github.com:holdennguyen/homelab.git
    targetRevision: HEAD
    path: k8s/apps/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
