apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/part-of: vikunja
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vikunja
      app.kubernetes.io/part-of: vikunja
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
