apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - dashboards/dashboard-homelab-overview.yaml
  - dashboards/dashboard-node-health.yaml
  - dashboards/dashboard-network.yaml
  - dashboards/dashboard-argocd.yaml
  - dashboards/dashboard-authentik.yaml
  - dashboards/dashboard-infisical.yaml
  - rules/alerts-argocd.yaml
  - rules/alerts-certificates.yaml
  - rules/alerts-nodes.yaml
  - rules/alerts-pods.yaml
  - rules/alerts-prometheus.yaml
  - rules/alerts-pvc.yaml
  - rules/recording-namespace.yaml
  - rules/recording-requests.yaml
